db:
  image: postgres
  volumes:
    - "./data:/var/lib/postgresql/data"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

admin:
  build: ./admin
  links:
    - db

api:
  build: ./api
  links:
    - db

web:
  build: ./web
  volumes_from:
    - admin
  ports:
    - "80:80"
  links:
    - admin
    - api